'use client';

import { Clock, ExternalLink, Facebook, Instagram, MapPin, MessageCircle, Phone, PhoneCall, Send, ShieldCheck, Sparkles, Star, Twitter, Youtube } from 'lucide-react';
import * as Icons from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export function StoreInformationSections({ store, brand, details, theme, onScroll, onMarketplace, onSearchAll, onNotify }) {
  return (
    <>
      <section className="container mt-14"><SectionTitle title={`Why choose ${store.name}?`} subtitle={`${brand.yearsInBusiness} years of serving your community`} theme={theme} /><div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{brand.whyChoose.map((item, index) => { const Icon = Icons[item.icon] || Icons.Sparkles; return <Card key={`${item.title}-${index}`} className="p-5 text-center hover:shadow-card transition"><div className="w-14 h-14 mx-auto rounded-2xl flex items-center justify-center mb-3" style={{ background: theme.accent, color: theme.primary }}><Icon className="w-6 h-6" /></div><div className="font-bold">{item.title}</div><div className="text-xs text-muted-foreground mt-1">{item.desc}</div></Card>; })}</div></section>

      <section className="container mt-14"><SectionTitle title="What our customers say" subtitle={`${store.reviews.toLocaleString()}+ happy customers`} theme={theme} /><div className="grid md:grid-cols-3 gap-4">{brand.testimonials.map((testimonial, index) => <Card key={`${testimonial.n}-${index}`} className="p-5"><div className="flex text-amber-500 mb-2">{[...Array(testimonial.r)].map((_, starIndex) => <Star key={starIndex} className="w-4 h-4 fill-current" />)}</div><p className="text-sm leading-relaxed">"{testimonial.t}"</p><div className="mt-4 flex items-center gap-3 pt-3 border-t border-border"><div className="w-9 h-9 rounded-full flex items-center justify-center text-white font-bold" style={{ background: theme.primary }}>{testimonial.n.charAt(0)}</div><div><div className="font-semibold text-sm">{testimonial.n}</div><div className="text-xs text-muted-foreground">{testimonial.role}</div></div></div></Card>)}</div></section>

      <section id="about" className="container mt-14"><div className="grid md:grid-cols-2 gap-8 items-center"><div><div className="text-xs uppercase font-bold tracking-wider" style={{ color: theme.primary }}>About {store.name}</div><h2 className="text-2xl md:text-3xl font-extrabold mt-2">Serving families since {brand.established}</h2><p className="text-sm md:text-base text-muted-foreground mt-3 leading-relaxed">{details.description}</p><div className="grid grid-cols-3 gap-3 mt-6"><MiniStat n={`${brand.yearsInBusiness}+`} label="Years" color={theme.primary} /><MiniStat n={details.ordersCompleted} label="Orders" color={theme.primary} /><MiniStat n={`${details.products.toLocaleString()}+`} label="Products" color={theme.primary} /></div><div className="mt-5 flex items-center gap-3 p-3 rounded-xl border" style={{ borderColor: theme.primary, background: theme.accent }}><img src={brand.ownerImage} className="w-14 h-14 rounded-full object-cover shrink-0" alt={brand.ownerName} /><div><div className="font-bold">{brand.ownerName}</div><div className="text-xs text-muted-foreground">{brand.ownerTitle} · License No: {brand.licenseNo}</div></div></div></div><div className="relative"><img src={brand.banner} className="rounded-2xl w-full h-72 object-cover shadow-card" alt={store.name} /><div className="absolute bottom-4 right-4 bg-background rounded-xl px-3 py-2 shadow-lg text-xs"><div className="font-bold flex items-center gap-1"><ShieldCheck className="w-3.5 h-3.5" style={{ color: theme.primary }} /> Verified Pharmacy</div><div className="text-muted-foreground mt-0.5">License: {brand.licenseNo}</div></div></div></div></section>

      <section id="contact" className="container mt-14"><SectionTitle title="Visit us or get in touch" subtitle="We are here to help — always" theme={theme} /><div className="grid md:grid-cols-2 gap-4"><Card className="p-5 space-y-3"><ContactRow icon={MapPin} label="Address" value={`${store.address} · Delivery radius ${details.deliveryRadius}`} color={theme.primary} /><ContactRow icon={Clock} label="Store Hours" value={store.hours} color={theme.primary} /><ContactRow icon={PhoneCall} label="Call" value={brand.contact} color={theme.primary} href={`tel:${brand.contact}`} /><ContactRow icon={MessageCircle} label="WhatsApp" value={brand.whatsapp} color={theme.primary} href={`https://wa.me/${brand.whatsapp.replace(/\D/g, '')}`} /><div className="pt-3 border-t border-border"><div className="text-xs text-muted-foreground mb-2 font-semibold uppercase">Send us a message</div><div className="flex gap-2"><Input placeholder="Your message..." className="h-10" /><Button className="rounded-full text-white h-10 px-4" style={{ background: theme.primary }}><Send className="w-4 h-4" /></Button></div></div></Card><Card className="overflow-hidden"><div className="relative h-72 md:h-full min-h-[280px] flex items-center justify-center" style={{ background: theme.accent }}><div className="flex flex-col items-center"><div className="w-10 h-10 rounded-full flex items-center justify-center shadow-glow" style={{ background: theme.primary }}><MapPin className="w-5 h-5 text-white" /></div><div className="mt-2 bg-background px-3 py-1.5 rounded-full text-xs font-bold shadow" style={{ color: theme.primary }}>{store.name}</div></div><a href={`https://maps.google.com/?q=${encodeURIComponent(store.address)}`} target="_blank" rel="noreferrer" className="absolute bottom-3 right-3 bg-background rounded-full px-3 py-1.5 text-xs font-semibold shadow inline-flex items-center gap-1 hover:shadow-md"><ExternalLink className="w-3 h-3" /> Directions</a></div></Card></div></section>

      <section className="container mt-14"><NotFoundBlock store={store} theme={theme} onSearchAll={onSearchAll} onNotify={onNotify} /></section>
      <StoreFooter store={store} brand={brand} details={details} theme={theme} onMarketplace={onMarketplace} onScroll={onScroll} />
    </>
  );
}

export function SectionTitle({ title, subtitle, theme }) { return <div className="mb-4"><h2 className="text-xl md:text-2xl font-extrabold tracking-tight" style={{ color: theme.dark || 'inherit' }}>{title}</h2>{subtitle && <p className="text-sm text-muted-foreground mt-0.5">{subtitle}</p>}</div>; }
function MiniStat({ n, label, color }) { return <div className="text-center p-3 rounded-xl bg-muted/40"><div className="text-2xl font-extrabold" style={{ color }}>{n}</div><div className="text-xs text-muted-foreground">{label}</div></div>; }
function ContactRow({ icon: Icon, label, value, color, href = undefined }) { const Wrapper = href ? 'a' : 'div'; return <Wrapper href={href} target={href?.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="flex items-start gap-3 p-2 rounded-lg hover:bg-muted/50 transition"><div className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style={{ background: `${color}20`, color }}><Icon className="w-4 h-4" /></div><div className="min-w-0"><div className="text-[11px] uppercase font-bold text-muted-foreground">{label}</div><div className="text-sm font-medium truncate">{value}</div></div></Wrapper>; }
function NotFoundBlock({ store, theme, onSearchAll, onNotify }) { return <div className="rounded-2xl p-6 md:p-8 text-center" style={{ background: theme.accent }}><div className="text-5xl mb-3">🔍</div><h2 className="text-xl md:text-2xl font-bold">Can't find your medicine at {store.name}?</h2><p className="text-sm text-muted-foreground mt-2 max-w-lg mx-auto">Our pharmacist can source it for you, or you can check other verified pharmacies nearby.</p><div className="mt-5 flex flex-col sm:flex-row gap-2 justify-center"><Button size="lg" onClick={onNotify} className="rounded-full text-white font-semibold" style={{ background: theme.primary }}><Sparkles className="w-4 h-4 mr-2" /> Notify me when available</Button><Button size="lg" variant="outline" onClick={onSearchAll} className="rounded-full font-semibold border-2" style={{ borderColor: theme.primary, color: theme.primary }}>Search across all Lylac One pharmacies</Button></div></div>; }
function StoreFooter({ store, brand, details, theme, onMarketplace, onScroll }) { return <footer className="mt-14 text-white" style={{ background: theme.dark }}><div className="container py-10 grid md:grid-cols-4 gap-8"><div className="md:col-span-2"><div className="font-bold text-lg">{store.name}</div><div className="text-xs opacity-80 italic">{brand.slogan}</div><p className="text-sm opacity-80 mt-3 max-w-md">{details.description}</p><div className="mt-4 flex items-center gap-2"><SocialIcon icon={Facebook} /><SocialIcon icon={Instagram} /><SocialIcon icon={Twitter} /><SocialIcon icon={Youtube} /></div></div><div><h3 className="font-bold text-sm uppercase mb-3">Store</h3><ul className="space-y-2 text-sm opacity-80"><li><Clock className="inline w-3.5 h-3.5 mr-2" />{store.hours}</li><li><MapPin className="inline w-3.5 h-3.5 mr-2" />{store.address}</li><li><Phone className="inline w-3.5 h-3.5 mr-2" />{brand.contact}</li></ul></div><div><h3 className="font-bold text-sm uppercase mb-3">Policies</h3><ul className="space-y-2 text-sm opacity-80"><li>Privacy Policy</li><li>Terms & Conditions</li><li>Return Policy</li><li onClick={() => onScroll('about')} className="cursor-pointer">About Us</li><li onClick={() => onScroll('contact')} className="cursor-pointer">Contact Us</li></ul></div></div><div className="border-t border-white/10 py-4 text-center text-xs opacity-80"><button onClick={onMarketplace}>Powered by <span className="font-bold text-white">Lylac One</span></button></div></footer>; }
function SocialIcon({ icon: Icon }) { return <button aria-label="Social media" className="w-9 h-9 rounded-full bg-white/10 hover:bg-white/20 flex items-center justify-center transition"><Icon className="w-4 h-4" /></button>; }
