// Mock data for Lylac One pharmacy marketplace

export const CATEGORIES = [
  { id: 'prescription', name: 'Prescription', icon: 'FileText', color: 'bg-rose-100 text-rose-600' },
  { id: 'otc', name: 'OTC', icon: 'Pill', color: 'bg-blue-100 text-blue-600' },
  { id: 'diabetes', name: 'Diabetes', icon: 'Droplet', color: 'bg-purple-100 text-purple-600' },
  { id: 'heart', name: 'Heart', icon: 'Heart', color: 'bg-red-100 text-red-600' },
  { id: 'baby', name: 'Baby Care', icon: 'Baby', color: 'bg-pink-100 text-pink-600' },
  { id: 'personal', name: 'Personal Care', icon: 'Sparkles', color: 'bg-fuchsia-100 text-fuchsia-600' },
  { id: 'vitamins', name: 'Vitamins', icon: 'Zap', color: 'bg-amber-100 text-amber-600' },
  { id: 'skin', name: 'Skin Care', icon: 'Sun', color: 'bg-orange-100 text-orange-600' },
  { id: 'hair', name: 'Hair Care', icon: 'Wind', color: 'bg-emerald-100 text-emerald-600' },
  { id: 'women', name: "Women's Health", icon: 'Flower', color: 'bg-pink-100 text-pink-600' },
  { id: 'men', name: "Men's Health", icon: 'User', color: 'bg-indigo-100 text-indigo-600' },
  { id: 'ayurvedic', name: 'Ayurvedic', icon: 'Leaf', color: 'bg-green-100 text-green-600' },
  { id: 'devices', name: 'Medical Devices', icon: 'Stethoscope', color: 'bg-cyan-100 text-cyan-600' },
  { id: 'surgical', name: 'Surgical', icon: 'Scissors', color: 'bg-slate-100 text-slate-600' },
  { id: 'nutrition', name: 'Nutrition', icon: 'Apple', color: 'bg-lime-100 text-lime-600' },
];

export const HEALTH_CONCERNS = [
  { id: 'fever', name: 'Fever', emoji: '🤒' },
  { id: 'cold', name: 'Cold', emoji: '🤧' },
  { id: 'cough', name: 'Cough', emoji: '😷' },
  { id: 'diabetes', name: 'Diabetes', emoji: '💉' },
  { id: 'bp', name: 'Blood Pressure', emoji: '❤️' },
  { id: 'pain', name: 'Pain Relief', emoji: '💊' },
  { id: 'stomach', name: 'Stomach Care', emoji: '🫀' },
  { id: 'skin', name: 'Skin', emoji: '✨' },
  { id: 'eye', name: 'Eye Care', emoji: '👁️' },
  { id: 'immunity', name: 'Immunity', emoji: '🛡️' },
];

export const PHARMACIES = [
  {
    id: 'ph-1',
    slug: 'apollo-247',
    name: 'Apollo 24|7 Pharmacy',
    image: 'https://images.pexels.com/photos/32116001/pexels-photo-32116001.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    logo: 'A',
    rating: 4.8,
    reviews: 2340,
    distance: '0.8 km',
    deliveryTime: '15 min',
    isOpen: true,
    freeDelivery: true,
    minOrder: 99,
    discount: '20% OFF',
    categories: ['Prescription', 'OTC', 'Wellness'],
    address: 'MG Road, Bengaluru',
    hours: '24 hours',
  },
  {
    id: 'ph-2',
    slug: 'medplus',
    name: 'MedPlus Health Store',
    image: 'https://images.pexels.com/photos/37126968/pexels-photo-37126968.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    logo: 'M',
    rating: 4.6,
    reviews: 1820,
    distance: '1.2 km',
    deliveryTime: '22 min',
    isOpen: true,
    freeDelivery: true,
    minOrder: 149,
    discount: '15% OFF',
    categories: ['Prescription', 'Baby Care', 'Nutrition'],
    address: 'Koramangala, Bengaluru',
    hours: '8 AM - 11 PM',
  },
  {
    id: 'ph-3',
    slug: 'wellness-forever',
    name: 'Wellness Forever',
    image: 'https://images.pexels.com/photos/33016276/pexels-photo-33016276.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    logo: 'W',
    rating: 4.7,
    reviews: 980,
    distance: '1.5 km',
    deliveryTime: '25 min',
    isOpen: true,
    freeDelivery: false,
    minOrder: 199,
    discount: '10% OFF',
    categories: ['Ayurvedic', 'Personal Care', 'Vitamins'],
    address: 'Indiranagar, Bengaluru',
    hours: '9 AM - 10 PM',
  },
  {
    id: 'ph-4',
    slug: 'netmeds-local',
    name: 'Netmeds Local',
    image: 'https://images.pexels.com/photos/8667531/pexels-photo-8667531.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    logo: 'N',
    rating: 4.5,
    reviews: 1560,
    distance: '2.1 km',
    deliveryTime: '30 min',
    isOpen: true,
    freeDelivery: true,
    minOrder: 99,
    discount: '25% OFF',
    categories: ['Prescription', 'Diabetes', 'Heart'],
    address: 'HSR Layout, Bengaluru',
    hours: '7 AM - 12 AM',
  },
  {
    id: 'ph-5',
    slug: '1mg-pharmacy',
    name: '1mg Pharmacy',
    image: 'https://images.pexels.com/photos/32116001/pexels-photo-32116001.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    logo: '1',
    rating: 4.9,
    reviews: 3200,
    distance: '2.4 km',
    deliveryTime: '35 min',
    isOpen: false,
    freeDelivery: true,
    minOrder: 199,
    discount: '18% OFF',
    categories: ['Prescription', 'Lab Tests', 'Consultation'],
    address: 'Whitefield, Bengaluru',
    hours: '8 AM - 10 PM',
  },
];

export const MEDICINES = [
  {
    id: 'med-1', name: 'Dolo 650', brand: 'Micro Labs', image: 'https://images.pexels.com/photos/51929/medications-cure-tablets-pharmacy-51929.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 32, mrp: 40, discount: 20, rx: false, pack: 'Strip of 15 tablets', rating: 4.7, reviews: 1240,
    composition: 'Paracetamol 650mg', uses: 'Fever, mild to moderate pain', dosage: '1 tablet every 6-8 hours',
    sideEffects: 'Rare: nausea, rash', manufacturer: 'Micro Labs Ltd.', category: 'otc', concern: 'fever',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-2', name: 'Crocin Advance', brand: 'GSK', image: 'https://images.pexels.com/photos/3873150/pexels-photo-3873150.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 45, mrp: 55, discount: 18, rx: false, pack: 'Strip of 15 tablets', rating: 4.6, reviews: 890,
    composition: 'Paracetamol 500mg', uses: 'Headache, fever, body ache', dosage: '1-2 tablets every 4-6 hours',
    sideEffects: 'Rare: allergic reaction', manufacturer: 'GlaxoSmithKline', category: 'otc', concern: 'fever',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-3', name: 'Cetzine Tablet', brand: 'Dr. Reddy\'s', image: 'https://images.pexels.com/photos/31406904/pexels-photo-31406904.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 28, mrp: 45, discount: 38, rx: false, pack: 'Strip of 10 tablets', rating: 4.5, reviews: 560,
    composition: 'Cetirizine 10mg', uses: 'Allergy, cold, sneezing', dosage: '1 tablet daily',
    sideEffects: 'Drowsiness, dry mouth', manufacturer: 'Dr. Reddy\'s Labs', category: 'otc', concern: 'cold',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-4', name: 'Benadryl Cough Syrup', brand: 'Johnson & Johnson', image: 'https://images.pexels.com/photos/7460048/pexels-photo-7460048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 120, mrp: 145, discount: 17, rx: false, pack: 'Bottle of 100ml', rating: 4.4, reviews: 320,
    composition: 'Diphenhydramine + Ammonium Chloride', uses: 'Cough, throat irritation', dosage: '10ml thrice daily',
    sideEffects: 'Drowsiness', manufacturer: 'Johnson & Johnson', category: 'otc', concern: 'cough',
    inStock: true, fastDelivery: false,
  },
  {
    id: 'med-5', name: 'Glycomet 500mg', brand: 'USV', image: 'https://images.pexels.com/photos/51929/medications-cure-tablets-pharmacy-51929.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 65, mrp: 78, discount: 17, rx: true, pack: 'Strip of 20 tablets', rating: 4.8, reviews: 1560,
    composition: 'Metformin 500mg', uses: 'Type 2 Diabetes', dosage: 'As prescribed',
    sideEffects: 'Nausea, stomach upset', manufacturer: 'USV Pvt Ltd', category: 'diabetes', concern: 'diabetes',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-6', name: 'Ecosprin 75mg', brand: 'USV', image: 'https://images.pexels.com/photos/3873150/pexels-photo-3873150.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 12, mrp: 18, discount: 33, rx: true, pack: 'Strip of 14 tablets', rating: 4.7, reviews: 980,
    composition: 'Aspirin 75mg', uses: 'Heart attack prevention', dosage: '1 tablet daily',
    sideEffects: 'Stomach irritation', manufacturer: 'USV Pvt Ltd', category: 'heart', concern: 'bp',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-7', name: 'Vitamin C Chewable', brand: 'HealthKart', image: 'https://images.pexels.com/photos/7460048/pexels-photo-7460048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 199, mrp: 299, discount: 33, rx: false, pack: 'Bottle of 60 tablets', rating: 4.6, reviews: 2100,
    composition: 'Vitamin C 500mg', uses: 'Immunity boost', dosage: '1 tablet daily',
    sideEffects: 'None', manufacturer: 'HealthKart', category: 'vitamins', concern: 'immunity',
    inStock: true, fastDelivery: true,
  },
  {
    id: 'med-8', name: 'Volini Pain Relief Gel', brand: 'Ranbaxy', image: 'https://images.pexels.com/photos/31406904/pexels-photo-31406904.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    price: 145, mrp: 175, discount: 17, rx: false, pack: 'Tube of 30g', rating: 4.5, reviews: 450,
    composition: 'Diclofenac 1%', uses: 'Muscle pain, sprains', dosage: 'Apply 2-3 times daily',
    sideEffects: 'Skin irritation', manufacturer: 'Sun Pharma', category: 'otc', concern: 'pain',
    inStock: true, fastDelivery: true,
  },
];

export const OFFERS = [
  { id: 'off-1', title: 'FLAT 25% OFF', subtitle: 'On all Vitamins & Supplements', code: 'HEALTH25', bg: 'linear-gradient(135deg,#a855f7,#ec4899)' },
  { id: 'off-2', title: 'FREE Delivery', subtitle: 'On orders above ₹299', code: 'FREEDEL', bg: 'linear-gradient(135deg,#14b8a6,#10b981)' },
  { id: 'off-3', title: '₹100 OFF', subtitle: 'First Order Discount', code: 'FIRST100', bg: 'linear-gradient(135deg,#f59e0b,#f97316)' },
  { id: 'off-4', title: 'Buy 2 Get 1', subtitle: 'On Personal Care items', code: 'B2G1', bg: 'linear-gradient(135deg,#f43f5e,#ef4444)' },
];

export const SERVICES = [
  { id: 'sv-1', name: 'Doctor Consultation', icon: 'Stethoscope', desc: 'Talk to a doctor in 15 min', color: 'bg-blue-50 text-blue-600' },
  { id: 'sv-2', name: 'Lab Tests', icon: 'FlaskConical', desc: 'Home sample collection', color: 'bg-purple-50 text-purple-600' },
  { id: 'sv-3', name: 'Health Records', icon: 'FolderHeart', desc: 'Digital vault', color: 'bg-emerald-50 text-emerald-600' },
  { id: 'sv-4', name: 'Medicine Reminder', icon: 'Bell', desc: 'Never miss a dose', color: 'bg-amber-50 text-amber-600' },
  { id: 'sv-5', name: 'Refill Prescription', icon: 'RefreshCw', desc: 'One-tap reorder', color: 'bg-rose-50 text-rose-600' },
  { id: 'sv-6', name: 'Health Articles', icon: 'BookOpen', desc: 'Expert-verified content', color: 'bg-cyan-50 text-cyan-600' },
];

export const ARTICLES = [
  { id: 'ar-1', title: '10 Foods That Boost Immunity Naturally', image: 'https://images.pexels.com/photos/7460048/pexels-photo-7460048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=600', category: 'Nutrition', readTime: '5 min' },
  { id: 'ar-2', title: 'Managing Diabetes: A Complete Guide', image: 'https://images.pexels.com/photos/3873150/pexels-photo-3873150.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=600', category: 'Diabetes', readTime: '8 min' },
  { id: 'ar-3', title: 'Winter Skincare: Doctor Approved Tips', image: 'https://images.pexels.com/photos/31406904/pexels-photo-31406904.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=600', category: 'Skin Care', readTime: '4 min' },
];

export const TRENDING_SEARCHES = ['Dolo 650', 'Vitamin C', 'Blood Pressure Monitor', 'Insulin', 'Face Wash', 'Protein Powder'];
export const RECENT_SEARCHES = ['Crocin', 'Cetzine', 'Multivitamin'];


// Extra store details keyed by pharmacy id

// Per-pharmacy branding & theme — each storefront looks like its own website
export const STORE_BRAND = {
  'ph-1': {
    slogan: "India's Trusted 24×7 Pharmacy Since 1987",
    tagline: 'Genuine medicines, delivered any hour of the day.',
    yearsInBusiness: 38,
    established: 1987,
    licenseNo: 'KA-B-B/2020/12345',
    ownerName: 'Dr. Prathap C. Reddy',
    ownerTitle: 'Founder & Chief Pharmacist',
    ownerImage: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=400',
    contact: '+91 80 4021 4021',
    whatsapp: '+91 80 4021 4021',
    theme: {
      primary: '#0F766E', secondary: '#0EA5E9', accent: '#ECFEFF', dark: '#134E4A',
      hero: 'linear-gradient(135deg, #0F766E 0%, #0EA5E9 100%)',
      font: 'Inter, sans-serif',
      style: 'trusted-medical',
    },
    banner: 'https://images.pexels.com/photos/8867432/pexels-photo-8867432.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=1400',
    heroImage: 'https://images.pexels.com/photos/7188918/pexels-photo-7188918.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    whyChoose: [
      { icon: 'ShieldCheck', title: '100% Genuine', desc: 'Every medicine verified by our pharmacists.' },
      { icon: 'Clock', title: '15-min Delivery', desc: 'Round-the-clock delivery to your doorstep.' },
      { icon: 'Award', title: '38 Years Legacy', desc: 'Trusted by 20L+ families across India.' },
      { icon: 'Stethoscope', title: 'Free Doctor Chat', desc: 'Talk to doctors free with every order.' },
    ],
    testimonials: [
      { n: 'Sneha R.', role: 'Regular Customer', r: 5, t: 'Apollo has been my go-to for 8 years. Never a single issue.' },
      { n: 'Rajesh V.', role: 'Diabetic Patient', r: 5, t: 'They deliver my insulin at odd hours — literal lifesavers.' },
      { n: 'Meena K.', role: 'Senior Citizen', r: 5, t: 'The delivery boys are so respectful. Feels like family.' },
    ],
  },
  'ph-2': {
    slogan: 'Health Karo Save Karo',
    tagline: 'Your neighbourhood chemist — bigger savings, bigger smiles.',
    yearsInBusiness: 24,
    established: 2000,
    licenseNo: 'KA-B-B/2019/56789',
    ownerName: 'Madhukar Gangadi',
    ownerTitle: 'Founder & CEO',
    ownerImage: 'https://images.pexels.com/photos/6749773/pexels-photo-6749773.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=400',
    contact: '+91 80 4041 4041',
    whatsapp: '+91 80 4041 4041',
    theme: {
      primary: '#DC2626', secondary: '#F59E0B', accent: '#FEF2F2', dark: '#7F1D1D',
      hero: 'linear-gradient(135deg, #DC2626 0%, #F59E0B 100%)',
      font: 'Inter, sans-serif',
      style: 'value-neighborhood',
    },
    banner: 'https://images.pexels.com/photos/6941883/pexels-photo-6941883.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=1400',
    heroImage: 'https://images.pexels.com/photos/3985163/pexels-photo-3985163.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    whyChoose: [
      { icon: 'BadgePercent', title: 'Up to 25% Off', desc: 'On every prescription order, always.' },
      { icon: 'Truck', title: 'Same-Day Delivery', desc: 'Order before 6 PM, get it today.' },
      { icon: 'Users', title: '3,000+ Stores', desc: "India's largest neighbourhood chain." },
      { icon: 'PhoneCall', title: 'Pharmacist on Call', desc: 'Free consultation with every order.' },
    ],
    testimonials: [
      { n: 'Kavya D.', role: 'Homemaker', r: 5, t: 'MedPlus discounts save me ₹500+ every month on family medicines.' },
      { n: 'Ashok P.', role: 'BP patient', r: 4, t: 'Consistent quality and always in stock.' },
      { n: 'Ranjini M.', role: 'Working professional', r: 5, t: 'They know me by name at my local store. Refreshing.' },
    ],
  },
  'ph-3': {
    slogan: 'Naturally Yours, Forever',
    tagline: 'Where Ayurveda meets modern wellness.',
    yearsInBusiness: 15,
    established: 2009,
    licenseNo: 'KA-B-A/2021/22344',
    ownerName: 'Dr. Ananya Iyer',
    ownerTitle: 'Ayurvedic Pharmacist',
    ownerImage: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=400',
    contact: '+91 80 4051 5151',
    whatsapp: '+91 80 4051 5151',
    theme: {
      primary: '#16A34A', secondary: '#84CC16', accent: '#F0FDF4', dark: '#14532D',
      hero: 'linear-gradient(135deg, #16A34A 0%, #84CC16 100%)',
      font: '"DM Serif Display", serif',
      style: 'wellness-natural',
    },
    banner: 'https://images.pexels.com/photos/4207892/pexels-photo-4207892.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=1400',
    heroImage: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    whyChoose: [
      { icon: 'Leaf', title: '100% Natural', desc: 'Certified organic Ayurvedic products.' },
      { icon: 'Sparkles', title: 'Curated Wellness', desc: 'Handpicked by our Ayurveda experts.' },
      { icon: 'HeartHandshake', title: 'Personalised Care', desc: 'Free Prakriti assessment for every customer.' },
      { icon: 'Recycle', title: 'Eco Packaging', desc: 'Biodegradable & recyclable delivery.' },
    ],
    testimonials: [
      { n: 'Divya S.', role: 'Yoga Instructor', r: 5, t: 'The best Ayurvedic products I have used. My skin has transformed.' },
      { n: 'Krishnan V.', role: 'Retired teacher', r: 5, t: 'Feels like the old-world pharmacies with modern convenience.' },
    ],
  },
  'ph-4': {
    slogan: "India's Trusted Online Chemist",
    tagline: 'Save more. Live better. Netmeds delivers.',
    yearsInBusiness: 10,
    established: 2015,
    licenseNo: 'KA-B-C/2022/98761',
    ownerName: 'Pradeep Dadha',
    ownerTitle: 'Founder',
    ownerImage: 'https://images.pexels.com/photos/6749773/pexels-photo-6749773.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=400',
    contact: '+91 80 4061 6161',
    whatsapp: '+91 80 4061 6161',
    theme: {
      primary: '#EA580C', secondary: '#0891B2', accent: '#FFF7ED', dark: '#7C2D12',
      hero: 'linear-gradient(135deg, #EA580C 0%, #0891B2 100%)',
      font: 'Inter, sans-serif',
      style: 'digital-value',
    },
    banner: 'https://images.pexels.com/photos/6941884/pexels-photo-6941884.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=1400',
    heroImage: 'https://images.pexels.com/photos/4021775/pexels-photo-4021775.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    whyChoose: [
      { icon: 'BadgePercent', title: 'Up to 30% Off', desc: 'Biggest online pharmacy savings.' },
      { icon: 'Truck', title: 'Pan-India Delivery', desc: 'Serving 20,000+ pincodes.' },
      { icon: 'FlaskConical', title: 'Lab Tests at Home', desc: '2,000+ tests with home collection.' },
      { icon: 'ShieldCheck', title: 'Verified Pharmacists', desc: '250+ licensed pharmacists on staff.' },
    ],
    testimonials: [
      { n: 'Amit T.', role: 'IT Professional', r: 4, t: 'Great discounts and reliable delivery even to remote areas.' },
      { n: 'Priya B.', role: 'Mother of two', r: 5, t: 'Ordering baby care items has never been easier.' },
    ],
  },
  'ph-5': {
    slogan: 'Your Health. Our Priority.',
    tagline: 'From consultations to medicines, all in one place.',
    yearsInBusiness: 10,
    established: 2015,
    licenseNo: 'KA-B-B/2023/11223',
    ownerName: 'Prashant Tandon',
    ownerTitle: 'Co-founder & CEO',
    ownerImage: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=400&w=400',
    contact: '+91 80 4071 7171',
    whatsapp: '+91 80 4071 7171',
    theme: {
      primary: '#7C3AED', secondary: '#EC4899', accent: '#FAF5FF', dark: '#4C1D95',
      hero: 'linear-gradient(135deg, #7C3AED 0%, #EC4899 100%)',
      font: 'Inter, sans-serif',
      style: 'modern-digital',
    },
    banner: 'https://images.pexels.com/photos/5721612/pexels-photo-5721612.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=1400',
    heroImage: 'https://images.pexels.com/photos/7088521/pexels-photo-7088521.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
    whyChoose: [
      { icon: 'Stethoscope', title: 'Doctor Consult', desc: 'Consult 1000+ verified doctors online.' },
      { icon: 'FlaskConical', title: 'Diagnostic Tests', desc: 'Book any test from home.' },
      { icon: 'PillBottle', title: '15,000+ Medicines', desc: 'Widest catalog in India.' },
      { icon: 'HeartPulse', title: 'Chronic Care Plans', desc: 'Auto-refill your recurring meds.' },
    ],
    testimonials: [
      { n: 'Deepika H.', role: 'Fitness Coach', r: 5, t: 'The app experience is world-class. Delivery is lightning fast.' },
      { n: 'Manoj T.', role: 'IT Consultant', r: 5, t: 'Booked a lab test, got results in the app next day. Wow.' },
    ],
  },
};

export const STORE_DETAILS = {
  'ph-1': {
    description: 'Apollo 24|7 Pharmacy is India\'s largest trusted pharmacy chain. We offer 100% genuine medicines from licensed manufacturers with same-day delivery across Bengaluru.',
    products: 12500, categories: 15, ordersCompleted: '2.5L+', avgDelivery: '18 min',
    services: ['home-delivery', 'doctor-consult', 'rx-upload', 'health-packages', 'lab-tests'],
    contact: '+91 80 4021 4021', deliveryRadius: '10 km', paymentOptions: 'UPI, Cards, COD, Wallet',
    returnPolicy: '7-day return on unopened items only. Prescription medicines are non-returnable.',
    license: 'Drug License No: KA-B-B/2020/12345 · GSTIN: 29AABCA1234B1Z5', verified: true,
    ratingBreakdown: { 5: 78, 4: 15, 3: 5, 2: 1, 1: 1 },
    reviews: [
      { n: 'Priya S.', r: 5, t: 'Super fast delivery, medicines were sealed and genuine!', helpful: 24, d: '2 days ago' },
      { n: 'Rahul M.', r: 5, t: 'Best pharmacy in the neighbourhood. Always in stock.', helpful: 18, d: '5 days ago' },
      { n: 'Anita K.', r: 4, t: 'Great service, prescription verified in minutes.', helpful: 12, d: '1 week ago' },
      { n: 'Vikram J.', r: 5, t: 'Delivered in 15 min flat. Impressive!', helpful: 30, d: '2 weeks ago' },
    ],
  },
  'ph-2': {
    description: 'MedPlus is your trusted neighbourhood pharmacy. 24×7 chemist services with the largest selection of prescription and OTC medicines.',
    products: 9800, categories: 14, ordersCompleted: '1.8L+', avgDelivery: '22 min',
    services: ['home-delivery', 'rx-upload', 'health-packages'],
    contact: '+91 80 4041 4041', deliveryRadius: '8 km', paymentOptions: 'UPI, Cards, COD',
    returnPolicy: '5-day return policy on eligible items.',
    license: 'Drug License No: KA-B-B/2019/56789 · GSTIN: 29AABCM6789K2Z1', verified: true,
    ratingBreakdown: { 5: 72, 4: 18, 3: 7, 2: 2, 1: 1 },
    reviews: [
      { n: 'Kavya R.', r: 5, t: 'Consistent quality and quick delivery.', helpful: 20, d: '3 days ago' },
      { n: 'Suresh N.', r: 4, t: 'Good discounts on generic medicines.', helpful: 14, d: '1 week ago' },
    ],
  },
  'ph-3': {
    description: 'Wellness Forever specialises in Ayurvedic, vitamins and personal care products alongside allopathic medicines. Curated by wellness experts.',
    products: 7200, categories: 12, ordersCompleted: '95k+', avgDelivery: '25 min',
    services: ['home-delivery', 'doctor-consult', 'health-packages'],
    contact: '+91 80 4051 5151', deliveryRadius: '6 km', paymentOptions: 'UPI, Cards, COD, Wallet',
    returnPolicy: 'No returns on personal care and opened items.',
    license: 'Drug License No: KA-B-A/2021/22344 · GSTIN: 29AABCW3344L1Z9', verified: true,
    ratingBreakdown: { 5: 74, 4: 17, 3: 6, 2: 2, 1: 1 },
    reviews: [
      { n: 'Meera D.', r: 5, t: 'Best place for Ayurvedic products in the area.', helpful: 16, d: '4 days ago' },
    ],
  },
  'ph-4': {
    description: 'Netmeds Local brings the trust of India\'s biggest online pharmacy to your neighbourhood. Genuine medicines at up to 30% off.',
    products: 11400, categories: 13, ordersCompleted: '1.4L+', avgDelivery: '28 min',
    services: ['home-delivery', 'rx-upload', 'lab-tests'],
    contact: '+91 80 4061 6161', deliveryRadius: '9 km', paymentOptions: 'UPI, Cards, COD',
    returnPolicy: '7-day easy returns on non-medicinal items.',
    license: 'Drug License No: KA-B-C/2022/98761 · GSTIN: 29AABCN9876P3Z2', verified: true,
    ratingBreakdown: { 5: 70, 4: 20, 3: 7, 2: 2, 1: 1 },
    reviews: [
      { n: 'Arun V.', r: 4, t: 'Great discounts, occasional delays.', helpful: 10, d: '6 days ago' },
    ],
  },
  'ph-5': {
    description: '1mg Pharmacy — India\'s trusted digital healthcare platform. Get medicines, lab tests, and doctor consultations under one roof.',
    products: 15800, categories: 15, ordersCompleted: '3.2L+', avgDelivery: '32 min',
    services: ['home-delivery', 'doctor-consult', 'rx-upload', 'health-packages', 'lab-tests'],
    contact: '+91 80 4071 7171', deliveryRadius: '12 km', paymentOptions: 'UPI, Cards, COD, Wallet, EMI',
    returnPolicy: '30-day return on eligible items. Medicines non-returnable.',
    license: 'Drug License No: KA-B-B/2023/11223 · GSTIN: 29AABCO1122M1Z4', verified: true,
    ratingBreakdown: { 5: 82, 4: 12, 3: 4, 2: 1, 1: 1 },
    reviews: [
      { n: 'Deepa H.', r: 5, t: 'Excellent range and reliable service.', helpful: 25, d: '1 day ago' },
      { n: 'Manoj T.', r: 5, t: 'Lab test at home was a great experience.', helpful: 21, d: '3 days ago' },
    ],
  },
};


export const ADDRESSES = [
  { id: 'ad-1', label: 'Home', address: 'Flat 302, Skyline Apartments, MG Road, Bengaluru — 560001', phone: '+91 98765 43210', default: true },
  { id: 'ad-2', label: 'Office', address: 'Prestige Tech Park, Bellandur, Bengaluru — 560103', phone: '+91 98765 43210', default: false },
];

export const ORDERS = [
  {
    id: 'ORD-2451',
    date: '2025-06-04', status: 'Out for Delivery',
    pharmacy: 'Apollo 24|7 Pharmacy', items: 3, total: 486,
    timeline: [
      { step: 'Order Placed', time: '10:30 AM', done: true },
      { step: 'Accepted', time: '10:34 AM', done: true },
      { step: 'Packed', time: '10:52 AM', done: true },
      { step: 'Out for Delivery', time: '11:15 AM', done: true },
      { step: 'Delivered', time: 'Est. 11:45 AM', done: false },
    ],
    partner: { name: 'Ramesh K.', phone: '+91 98765 43210', rating: 4.9, vehicle: 'KA-05-EE-1234' },
  },
  {
    id: 'ORD-2440',
    date: '2025-05-28', status: 'Delivered',
    pharmacy: 'MedPlus Health Store', items: 5, total: 1245,
    timeline: [
      { step: 'Order Placed', time: 'May 28, 9:00 AM', done: true },
      { step: 'Delivered', time: 'May 28, 10:30 AM', done: true },
    ],
  },
];
